### ISSUE TITLE
Workplan - Final Milestone Anticipated Date

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#1931]
**Describe the bug**
the anticipated date for the end event for the current phase does not want to move. Check MUD BAY in Prod to see if you can reproduce.

**To Reproduce**

**Expected behavior**
we want the anticipated to be able to be changed for any phase, as long as it is not being put outside the legislated timeframe. an extension should change the boundary so the anticipated could be moved later.

**Screenshots**

**Additional context**

**Comment by dinesh-aot** [comment]
@Connor1892  This issue was already fixed in a different way in test environment. Can you try to reproduce this situation in test environment.

**Comment by carlygreenehill** [comment]
Blocked until we can confirm with @Connor1892 that this is still occurring in TEST

**Comment by dinesh-aot** [comment]
It is happening with Mud Bay Nature-Based Foreshore Enhancement - Exemption Order - Exemption Order in production
