### ISSUE TITLE
Issues Tab - Empty State

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#920]
**As a** user

**I want** to see when there are no issues associated with the Work

**so that** I can add them

### Scenario 1: 

GIVEN I am on the Issues tab of the Workplan
WHEN there is no Issues assigned to the Work
THEN I see the following text:

You don't have any Issues yet
Start adding your Issues

'+ Issue' (Primary)

### Scenario 2:
 
GIVEN I am on the Issues tab
WHEN I select the add Issues button
THEN I see the add Issues modal

### Scenario 3:
 
GIVEN I am on the Issues tab
WHEN I look at the right side
THEN I see the tabbed section:
- Reports Preview
- Notes (rich text)

### Scenario 4:
 
GIVEN I am on the Issues tab
WHEN I have the Report Preview tab open
THEN I see the following:
- 30-60-90 button (Primary)
- Referral Schedule button (ghost)
- Report Preview panel
    - Title (of selected report)
    - sub header (project description)
    - system generated project description
    - [Project Name] is in [Phase Name]
    - sub header (Status)
    - Status (pulled from Status Tab)
    - sub header (Issues)
    - preview box (with text: "Your Issues will appear here" (ghost text))

### Scenario 5:
 
GIVEN I am on the Issues tab
WHEN I have the Report Preview tab open AND select the Referral Schedule button
THEN I see the following:
- 30-60-90 button (Ghost)
- Referral Schedule button (Primary)
- Report Preview panel
    - Title (of selected report)
    - sub header (project description)
    - system generated project description
    - [Project Name] is in [Phase Name]
    - sub header (Status)
    - Status (pulled from Status Tab)
    - sub header (Issues)
    - preview box (with text: "Your Issues will appear here" (ghost text))

**Comment by Connor1892** [comment]
@maria-kuzmenko add pics

**Comment by maria-kuzmenko** [comment]
link to prototype

https://www.figma.com/file/yZk63tFMjpuCbYLCBpo7OT/Development-(Issues%2FStatus)?type=design&node-id=4771-9658&mode=design

**Comment by Connor1892** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/EPICtrack-63891ea941d309001fa292cf/issues/bcgov/EPIC.track/920?planning-poker) with Zenhub @TomChapmanGov @jadmsaadaot @saravanpa-aot

**Comment by maria-kuzmenko** [comment]
@jadmsaadaot , @TomChapmanGov 

same comments as for card #1106

+ Referral Schedule in preview says '30-60-90 Preview' and should say 'Referral Schedule Preview'

**Comment by maria-kuzmenko** [comment]
@Connor1892 

the fix for the comment will be implemented in #921

**Comment by jadmnsaad** [comment]
Referral Schedule in preview says '30-60-90 Preview' and should say 'Referral Schedule Preview' is fixed in the following task:

https://app.zenhub.com/workspaces/epictrack-63891ea941d309001fa292cf/issues/gh/bcgov/epic.track/921

**Comment by Connor1892** [comment]
For Scenario 3, the rich text is not saving
For Scenario 4 & 5, there is nothing on the reports preview tab for the status header or generated box
For Scenario 5, the Referral schedule still shows 30-60-90 in the preview

When switching between 30-60-90 and Referral Schedule the buttons change size. this can be made into an enhancement card if we want.

**Comment by maria-kuzmenko** [comment]
@Connor1892 

Scenario 3 - RTE card would cover that
Scenario 4&5 - we agreed with Jad that as there is no status, we'll leave it be for a while until the status is created
Scenario 5 would be covered in ticket 921

Buttons appearance we discussed with Jad, this should be universal for the whole application, so that should be a separate enhancement card

**Comment by Connor1892** [comment]
enhancement card made #1175
